linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - ineffassign
    - unused
    - misspell

linters-settings:
  gosec:
    excludes:
      - G402 # TLS InsecureSkipVerify (开发环境需要)

issues:
  exclude-dirs:
    - vendor
